### ISSUE TITLE
LSTD

### ISSUE THREAD

**Issue by GodefroyClair** [artix41/awesome-transfer-learning#13]
Hi,
Thank you for your review of ressources in transfer learning.
I recommend to add the paper "LSTD: A Low-Shot Transfer Detector for Object Detection" (https://arxiv.org/abs/1803.01529).
You can find the implementation in Caffe [here](https://github.com/Cassie94/LSTD).
It uses a mix of SSD & Faster R-CNN but the interest is more in the regularization techniques the authors have created.
Also there is an [implementation in Pytorch](https://github.com/JiasiWang/pytorch-lstd) but it's buggy and seems dead.
To be complete, there is an application of the LSTD for ["document layout analysis"/"document segmentation"](https://arxiv.org/abs/1808.07330) using text mining for the classifier.

Finally, there is a model called ["Zero-Shot Object Detection"](https://arxiv.org/abs/1804.04340) that could be interesting but I didn't read yet.

**Comment by artix41** [comment]
Sure, thanks, please do a PR :)

**Comment by artix41** [comment]
Issue solved
