### ISSUE TITLE
Adding GCA paper (ECML 2018) to the list

### ISSUE THREAD

**Issue by bamdevm** [artix41/awesome-transfer-learning#20]
I shall be glad if you could add the paper published at ECML 2018 https://link.springer.com/chapter/10.1007/978-3-030-10928-8_50 in your list. 

The algorithm name is "GCA". 
The title of the paper is "A Unified Framework for Domain Adaptation Using Metric Learning on Manifolds".

It should logically come in the section Subspace Learning under Unsupervised Domain Adaptation.

**Comment by artix41** [comment]
Done :)
